### ISSUE TITLE
AMD GPU Driver Support

### ISSUE THREAD

**Issue by Karto12** [valentinvanelslande/citra#344] opened 2018-03-18 19:52 UTC
Citra crash everytime in Monster Generation while you try to load an Character.
 I got an r9 280x with an fx-8350
with Shader Emulation  = CPU It work but low frame
and with Shader Emulation =GPU it crashes in the Loading screen
![crash](https://user-images.githubusercontent.com/37515940/37570253-f019d3e8-2aed-11e8-9ef0-b3fcf95356dd.PNG)
![cm](https://user-images.githubusercontent.com/37515940/37570318-b81610b4-2aee-11e8-8727-b658b2673f35.PNG)

**Comment by valentinvanelslande** [comment] 2018-03-18 22:22
duplicate of #341

**Closed by valentinvanelslande** 2018-03-18 22:22 UTC
