### ISSUE TITLE
Luigi's Mansion 2 crashes on boot

### ISSUE THREAD

**Issue by EmulationChannel** [valentinvanelslande/citra#434] opened 2018-09-02 22:28 UTC
Citra Valentin 521
[citra_log.txt](https://github.com/valentinvanelslande/citra/files/2343798/citra_log.txt)

**Comment by valentinvanelslande** [comment] 2018-09-02 22:29
duplicate of #433

**Comment by Nerboruto** [comment] 2018-09-03 17:02
run bad on master but not crash...

**Closed** 2018-09-14 00:00 UTC
Labels: A-cpu, T-crash, T-regression
